ignoreWorkspaceRootCheck: true
minimumReleaseAgeExcludePrune: true
trustPolicy: no-downgrade
autoInstallPeers: false

peerDependencyRules:
  ignoreMissing:
    - rollup

shellEmulator: true

packages:
  - playground
  - npm/wasm

allowBuilds:
  esbuild: true
  unrs-resolver: true
