import type { NativeBinding } from './api'
import type { TranspileOptions } from './types'
// The wasm loader is generated by `napi build --target wasm32-wasip1`
// (scripts/build-wasm.mjs) and ships in the @petrea/binding-wasm32-wasip1
// package. It instantiates the module at import time — when that fails (no
// fetch, missing asset) the import of this entry rejects, and no partial
// exports are observable.
import * as wasip1Loader from '@petrea/binding-wasm32-wasip1'

import { createApi } from './api'

export type { OnError, TranspileOptions, UnsupportedSyntax } from './types'

function loadWasmBinding(): NativeBinding {
  return wasip1Loader as unknown as NativeBinding
}

const api = createApi(loadWasmBinding)

/**
 * Constant `true`, kept for export parity with the main entry: the wasm
 * build instantiates at import time, so once this module loads at all the
 * transpilers are fully usable.
 */
export const nativeBindingAvailable = api.isAvailable

/**
 * WebAssembly entry point: the same Rust pipeline compiled to
 * `wasm32-wasip1`. The API mirrors the main entry exactly. Browsers already
 * resolve `petrea` here through the `browser` export condition; this
 * explicit entry forces it everywhere else.
 *
 * ```
 * import { transpile } from 'petrea/wasm'
 *
 * await transpile(`const a: number = 1`)
 * // 'const a         = 1'
 * ```
 */
export const transpile: (input: string, options?: TranspileOptions) => Promise<string>
  = api.transpile

export const transpileSync: (input: string, options?: TranspileOptions) => string
  = api.transpileSync
